# Generated by Django 4.0.4 on 2022-05-23 23:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('healpoints', models.FloatField(verbose_name='Жизни')),
                ('loot', models.CharField(max_length=40, verbose_name='Лут после противника')),
                ('race_b', models.CharField(max_length=40, verbose_name='Раса')),
            ],
            options={
                'verbose_name': 'Противник',
                'verbose_name_plural': 'Противники',
            },
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_hero', models.CharField(max_length=255, verbose_name='Имя антогониста')),
                ('hp', models.FloatField(verbose_name='Жизни')),
                ('lvl', models.FloatField(verbose_name='Уровень')),
                ('mana', models.FloatField(verbose_name='Мана')),
                ('race', models.CharField(max_length=40, verbose_name='Раса')),
            ],
            options={
                'verbose_name': 'Герой',
                'verbose_name_plural': 'Герои',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('descr', models.TextField(verbose_name='Описание уровня')),
                ('experience', models.FloatField(verbose_name='Количесвто опыта')),
                ('boss', models.ManyToManyField(to='gameapi.boss', verbose_name='Противник')),
                ('hero', models.ManyToManyField(to='gameapi.hero', verbose_name='Герой')),
            ],
            options={
                'verbose_name': 'Уровень',
                'verbose_name_plural': 'Уровени',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLevel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('descr', models.TextField(verbose_name='Описание уровня')),
                ('experience', models.FloatField(verbose_name='Количесвто опыта')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Уровень',
                'verbose_name_plural': 'historical Уровени',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalHero',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name_hero', models.CharField(max_length=255, verbose_name='Имя антогониста')),
                ('hp', models.FloatField(verbose_name='Жизни')),
                ('lvl', models.FloatField(verbose_name='Уровень')),
                ('mana', models.FloatField(verbose_name='Мана')),
                ('race', models.CharField(max_length=40, verbose_name='Раса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Герой',
                'verbose_name_plural': 'historical Герои',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBoss',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Имя')),
                ('description', models.TextField(verbose_name='Описание')),
                ('healpoints', models.FloatField(verbose_name='Жизни')),
                ('loot', models.CharField(max_length=40, verbose_name='Лут после противника')),
                ('race_b', models.CharField(max_length=40, verbose_name='Раса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Противник',
                'verbose_name_plural': 'historical Противники',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
